{% set name = "opty" %}
{% set version = "1.0.0" %}
{% set sha256 = "9eb5a53e1ca173bbe08f3f4553f0b5b568f1da0cc7f784657be0021f1c73816e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt
requirements:
  build:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.8.1
    - scipy >=0.14.1
    - sympy >=1.0.0
    - cython >=0.20.1
    - cyipopt >=0.1.7

test:
  imports:
    - opty
    - opty.direct_collocation
    - opty.parameter_identification
    - opty.utils
    - opty.tests
  files:
    - betts2003.py
  commands:
    - python betts2003.py

about:
  home: http://github.com/csu-hmc/opty
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Tools for optimizing dynamic systems using direct collocation.'
  description: |
    opty utilizes symbolic descriptions of ordinary differential equations
    expressed with SymPy to form the constraints needed to solve optimal
    control and parameter identification problems using the direct collocation
    method and non-linear programming. In general, if one can express the
    continuous first order ordinary differential equations of the system as
    symbolic expressions opty will automatically generate a function to
    efficiently evaluate the dynamical constraints and a function that
    evaluates the sparse Jacobian of the constraints, which have been optimized
    for speed and memory consumption. The translation of the dynamical system
    description to the NLP form, primarily the formation of the constraints and
    the Jabcobian of the constraints, manually is a time consuming and error
    prone process. opty eliminates both of those issues.
  dev_url: http://github.com/csu-hmc/opty

extra:
  recipe-maintainers:
    - moorepants
