{% set name = "opty" %}
{% set version = "1.5.0" %}
{% set sha256 = "804b60b4b295e78851f5d1db5d16701e1b631502644a07ece49209e74a2e275b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolatio -vv .
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=59.6.0
  run:
    - cyipopt >=1.1.0
    - cython >=0.29.28
    - numpy >=1.21.5
    - python
    - setuptools >=59.6.0
    - sympy >=1.9.1
  run_constrained:
    - matplotlib-base >=3.5.1
    - scipy >=1.8.0

test:
  requires:
    - {{ compiler('c') }}
    - pytest
    - scipy >=1.8.0
  imports:
    - opty
    - opty.direct_collocation
    - opty.parameter_identification
    - opty.utils
    - opty.tests
  files:
    - betts2003.py
    - helloworld.pyx
    - test_setup.py
  commands:
    - which python  # [unix]
    # NOTE : Try to build a simple Cython extension. ufuncify_matrix() does not
    # seem to print error info on this command with subprocess.call() and this
    # sample gives better feedback until ufuncify_matrix() is improved.
    - python test_setup.py build_ext --inplace
    - python -c "from opty.tests.test_utils import test_ufuncify_matrix;test_ufuncify_matrix()"  # [unix]
    - python betts2003.py

about:
  home: http://github.com/csu-hmc/opty
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tool for optimizing dynamic systems using direct collocation.
  description: |
    opty utilizes symbolic descriptions of differential algebraic equations
    expressed with SymPy_ to form the constraints needed to solve optimal
    control and parameter identification problems using the direct collocation
    method and nonlinear programming (NLP). In general, if one can express the
    continuous first order differential algebraic equations of the system as
    symbolic expressions, opty will automatically generate a function to
    efficiently evaluate the dynamical constraints and a function that
    evaluates the sparse Jacobian of the constraints, which have been optimized
    for speed and memory consumption. The translation of the dynamical system
    description to the NLP form, primarily the formation of the constraints and
    the Jacobian of the constraints, manually is a time consuming and error
    prone process. opty eliminates both of those issues.
  dev_url: http://github.com/csu-hmc/opty
  doc_url: http://opty.readthedocs.io/

extra:
  recipe-maintainers:
    - moorepants
