travis:
  secure:
    BINSTAR_TOKEN: YicGu3CURbXBvikQ4XNpA+g8rQB5o+SjqsPqs0ZAk39EuV5RVdY7NFK3DxnOOfsVXadNLzsmTAMDDMUq8SXPntZVQRAUIUC23bYOXwceQilxpUsBym3eDfHk/G1BcGygRp47lSOh6tkDJlshNlB9SSnHF6KGIRXJJQCW6xpSQ5s5YNJQPw0xS4BYXavANUiw0BMpQrIzkQD7lLzYNZUsGLJTZJQFLopY05FpG4colf59Q8lWnn2G6I74+APMx5woyTSRz75ostkf8hC1agSWwla+oOaWC+cer4PAFJ1jJxgu35ECoIwOvH4zJuTPdxQm3MLTpLxs1PzjcxkXXuLVIDoVG0SOZsI1LY/mTJvm0ODEbJlXvA73r/WOdfJ1AY/e4SmwZkWuOYHFoBh9FCXiLhgfQuDWxFqlVVswFZhOsAEpi20Uj0mIt/aHsBpA1rin/uHQIckzP8YrpJaxtjt3/98p2PyOvKFAM5Z4IGj3kJ+b7lPJM66xsDsdN2B2QunRxFtaIS2ucLMdijsXf48gogOA8+vXdbNKuwaEvrjcUBw/xMTM5C5PXgpfPJxvly+uaznBGR1ipqggYaUTzuQTQhnE+2tJPBrZ0T7PWyig3GD62Ks12ePvN7yijxkSEoGwVe775XllFTDK3ZlWzE24xy3iUdWBrAbkVuydNIqa7NE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
