travis:
  secure:
    BINSTAR_TOKEN: 0hR2CieB6q290bhr9FXXNKynHJm1yCV1TZwOCu6T5z4yZxW+GzZSVg+pKsWTLC5UkO/O1rIzKvluoEIkJC96vUCfpM4tQvXoKatEdi8czGRT0eZvKo0alAWT27v38Kkmvgc/sypnozOX+qTiKyg2mrVKU8dYXKCcEXTzphvk/oQfa3XQLv3PHRH2NpKxhETkY5nChelCngfMr/FzI+KgP445uGsek5S+OfgHcSjUJ3hyQgnGXwPPtGM7bX8DTC4moqHz3SHeERJG/0OudjvxJW9dqP0Tj2BozVhyESRJdtSaKJHxUFTKVX7JpHOo8ONRRA3hlxp53x2ilwzXbD7TU+hHcZZ2uWNaoSgw8QjR/kcpsU3mGk/fEUkfJjMkGFYr3VwGP+EZgQa1W4nqpSBZbYs73EziguLKUiHcqjjqpjLIqP5+ksdCd/sgSLsr7dxoR2aPJ8A+4woph2Mt4NFkELUxyobNBS+pGP/G91udRNnc5R8Hh2s0Yu3BCDBKCugkBUIZNEES2R3dZNefPfGHhZLau8SwgGvWw20CsnMdr2dfAnmWL7kw/pevINUWmT+DrSMNj88+yiG6oTr1ob92D/6m3YAgl3fvTt0KUoz8tys0O4c8ap3rJjZ2FTTeFfpg3uryRAkDjM8kvyW1GWkFCn2jjjN1I4iqytJrAFPI36o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
